### ISSUE TITLE
Flag is not refresh when the language is changed

### ISSUE THREAD

**Issue by manooweb** [polylang/polylang-gutenberg#10]
When we change the language in the "language" metabox the flag on the left is not changed and all other flags for each alternative languages are not updated.

**Comment by Chouby** [comment]
In my opinion, this is because post.js is dequeued by this plugin. Part of the code of post.js is useless and may cause conflict. Part of the code is still useful. The cases 'translations' and 'flag' in https://github.com/polylang/polylang/blob/2.3.5/js/post.js#L181-L203 must be still valid.
