### ISSUE TITLE
Link to translations must propose the right editor Gutenberg or Classic

### ISSUE THREAD

**Issue by manooweb** [polylang/polylang-gutenberg#12]
In the list of posts or in the Polylang metabox for editing the content in the right editor

**Comment by Chouby** [comment]
I propose to close this issue as it was meaningful in Gutenberg. But it's no more the case with WP 5.0 as WordPress does not include any possibility to select one editor or the other.

**Comment by manooweb** [comment]
Yes right !
It's useful only if we continuer to use both of the two editors together ie Gutenberg plugin on a WordPress version before 5.0
