### ISSUE TITLE
Preview post link with gutenberg and polylang does not work correctly in subdomains polylang configuration

### ISSUE THREAD

**Issue by manooweb** [polylang/polylang-gutenberg#14]
There is an admin-ajax call fail with the pll_xdata actions when polylang attempt to redirect for previewing the post in the correct language.
See issue #4959 in our internal tracking tool.

**Comment by Chouby** [comment]
I thoroughly tested and could not reproduce the issue. 
NB: The preview link generated by Gutenberg is the same as in the classic editor so I expect it to work the same way.
