### ISSUE TITLE
Categories and tags are not filtered per language

### ISSUE THREAD

**Issue by Chouby** [polylang/polylang-gutenberg#2]
In the sidebar, the Categories and Tags sections show all categories and all tags in all languages. It is expected that only the categories and tags in the language of the post are shown. 

The categories and tags list should also react to a modification of the language in the Languages metabox.

The issue was originally reported in https://github.com/polylang/polylang/issues/235

**Comment by manooweb** [comment]
Polylang Pro REST API module is necessary for working well. We did not implemented yet for Polylang
