### ISSUE TITLE
It is not possible to change the language of a created post

### ISSUE THREAD

**Issue by Chrystll** [polylang/polylang-gutenberg#21]
## Plugins activated
Gutenberg 4.1.0
Polylang Pro 2.4-beta1
Polylang With Gutenberg 0.2.0 (master)

## Issue description
It is not possible to change the language of a created post.

## Steps to reproduce 

1. Create a post in English then publish it.

2. Change the language post to French for example. The post is automatically updated and I obtain the French as post language and the "Post updated.View Post" message as here:

![screen1](https://user-images.githubusercontent.com/19824724/47508797-09ae6f00-d875-11e8-8e39-7f1f9a3b2664.png)

3. Check the post permalink: it is still in English "trunk-test.com/en/a-post/", see: 

![screen2](https://user-images.githubusercontent.com/19824724/47508930-5134fb00-d875-11e8-8efb-e497be539c1a.png)

When checking the post list, the post is still showing in English, see:

![screen3](https://user-images.githubusercontent.com/19824724/47509097-a709a300-d875-11e8-92a0-7c08de62b77d.png)

**Comment by manooweb** [comment]
Strange behaviour. It's something I tested.
