### ISSUE TITLE
The slug modified from the quick edit is overwritten

### ISSUE THREAD

**Issue by Chrystll** [polylang/polylang-gutenberg#25]
## Plugins activated & WordPress version
Polylang Pro 2.4-beta1 (block-editor branch)
WordPress 5.0-beta4-43896 (block mode editor)

## Issue description

The slug modified from the quick edit is overwritten when just updating the post or the page in editing mode.
This issue also happens when using Polylang with Gutenberg addon.
This issue doesn't happen with Polylang (free).
Issue reported here:https://github.com/WordPress/gutenberg/issues/10004

## Steps to reproduce the issue
1. Quick edit a page 'page in english' then modify the slug, here 'hello'.
2. Edit this page > the slug is still 'hello' > just update: the slug is modified to 'page-in-english'.

**Comment by phamquangbaoplus** [comment]
Same issue https://github.com/polylang/polylang-gutenberg/issues/20

**Comment by Chouby** [comment]
@phamquangbaoplus Thank you. I am sorry. had not read the issue that you opened. And it was reported a second time by another customer which makes @Chrystll open this issue. It will be fixed in Polylang Pro 2.4.1, before teh realse of WP 5.0.
