### ISSUE TITLE
Some HTML entities are not decoded in the language panel

### ISSUE THREAD

**Issue by benoitchantre** [polylang/polylang-gutenberg#27]
When a title contains HTML entities like `&`, `'`, ... their entity number is displayed (`&#038;`, `&lsquo;`, ...) in the translations fields.

The expected behaviour would be to display human readable characters.

Tested with:
- Polylang Pro 2.4
- [current version](https://github.com/polylang/polylang-gutenberg/commit/b335aa7eeb04d8bddeda14347944604152da4402) of Polylang-Gutenberg
- Gutenberg 4.4
- WP 4.9.8.

**Comment by manooweb** [comment]
This issue is now corrected by using context=edit parameter in REST API calls and using "raw"property of the title instead of "rendered"
