### ISSUE TITLE
Impossible to create a translated synchronized post

### ISSUE THREAD

**Issue by Chrystll** [polylang/polylang-gutenberg#32]
## Plugins activated
Gutenberg 4.6.1
Polylang Pro 2.5 (master)
Polylang with Gutenberg 0.3.0

## Issue description

It is not possible to create a translated synchronized post. A post is created but it is not linked by the translation

## Steps to reproduce the issue
1. Create an English post. You don't need to add some blocks.
2. Activate the synchronized content tool for the French language > then save your changes: the French syncnronized post is not displayed in the metabox even after refreshing the page.
3. Go back to the post list: the French post has been well created in the French but it is not linked by the translation.
![screen](https://user-images.githubusercontent.com/19824724/49873923-62ce6400-fe1d-11e8-8631-9ae1573c000f.png)

See also this: https://github.com/polylang/polylang-pro/issues/146

**Comment by manooweb** [comment]
Corrected in commit referenced above and need Polylang Pro 2.6dev to work well.
