### ISSUE TITLE
PHP notice thrown by Add preloading data for block editor waiting Polylang will be ready

### ISSUE THREAD

**Issue by Chrystll** [polylang/polylang-gutenberg#35]
## Plugins activated
Polylang Pro 2.5 master
Polylang With Gutenberg 0.4.0 master
WordPress 5.0.2

## Issue description
I get a php notice is thrown by the [commit](https://github.com/polylang/polylang-gutenberg/commit/fc209d1fa02c2edf287aeb4bc359835c5e83e29b) Add preloading data for block editor waiting Polylang will be ready.

`PHP Notice:  Undefined property: PLL_Language::$flag in /home/christelle/Documents/git/polylang-pro/admin/admin-base.php on line 377`

## Steps to reproduce
1. Activate both Polylang Pro and Polylang With Gutenberg.
2. Add or edit a page: the php notice is triggered.

**Comment by manooweb** [comment]
In fact the bug is in Polylang PRO REST API
See https://github.com/polylang/polylang-pro/issues/223
