### ISSUE TITLE
The autocomplete field allows to select posts which have already a translation

### ISSUE THREAD

**Issue by Chrystll** [polylang/polylang-gutenberg#37]
## Plugins activated
Polylang Pro 2.5
Polylang With Gutenberg 0.4
WordPress 5.0.2

## Issue description
The autocomplete field allows to select posts which have already a translation in this language. If a translation exists in this language thus the post shouldn't be displayed.

## Steps to reproduce the issue
1. Create a post and translate it in all the languages as:

2. Create another post then get back the translated post "Week at Annecy - German" and select it as here:
![screenshot-trunk-test com-2019 01 09-17-26-09](https://user-images.githubusercontent.com/19824724/50965347-fe60fc00-14d1-11e9-9084-ba95bfbf5f34.png)

3. Once it done, go to the posts list: now the post "Week at Annecy - German" is the translation of 2 English posts as shown here:
![screenshot-trunk-test com-2019 01 09-17-36-41](https://user-images.githubusercontent.com/19824724/50965355-06b93700-14d2-11e9-8b93-02c2ad2e6116.png)

**Comment by manooweb** [comment]
Note : look at the autocomplete used for the button block if it would be better to use.
Its use seems to be more simple and better correspond to our need.
