### ISSUE TITLE
Categories are always created in the default language

### ISSUE THREAD

**Issue by Chouby** [polylang/polylang-gutenberg#6]
It is possible to create a category directly in the Gütenberg sidebar (Add New Category link). I expect that this category is created in the same language as the current post being edited, but it is always aassigned the default language.

This is the same for tags (tags are created when entering a new tag in tag input field).

**Comment by manooweb** [comment]
I verified. Now, as the REST API is well called with the lang parameter the new category or the new tag is well created in the language selected in the language metabox.
